function subspaceL = labelPoints(subspace, dataGrid)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%BEGIN%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% The script can help users to get the labels of each  point of dataset with
% the help of the tree generated by CLIQUE.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%INPUT%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% subspace: the subpace (struct)
%    subspace.dimenInfor : the dimension information about the subpace
%    subspace.cells : the cells of the subspace
%    subspace.labels: the label of each cell
%  dataGrid : a matrix which indicated the grid that each point belongs to.
%             The NO.j dimension of NO.i point belongs to NO.dataGrid (i,j)
%             grid of the dimension(N-by-dimen)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%OUTPUT%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% subspaceL: the result of grouping ponits into clusters
%    subspaceL.dimenInfor : the dimension information about the subpace
%    subspaceL.labels: label of each points (N-by-1)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%VERSION%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Author: Shuai Wu
%  Date : July 16 2018 
%  E_mail: shuaiwu.ws@gmail.com
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%END%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
dimenInfor = subspace.dimenInfor;
cells = subspace.cells;
subspaceL.dimenInfor = dimenInfor;
N = size(dataGrid,1);
labels = zeros(N,1);
dimen = size(dimenInfor,2);
numCells = size(cells,1);
for i = 1:numCells
    isInCell = true(N,1);
    for j = 1:dimen
        isInCell = isInCell & (dataGrid(:,dimenInfor(j))>=cells(i,j,1))&...
           (dataGrid(:,dimenInfor(j))<=cells(i,j,2));
    end
    labels(isInCell,1) = subspace.labels(i);
end

subspaceL.labels = labels;
end