function clusterResult = obtainLabelByCLIQUE(clustersTree,dataGrid)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%BEGIN%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% The script can help users to get the labels of each  point of dataset with
% the help of the tree generated by CLIQUE.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%INPUT%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% clustersTree: the result of clustering (tree)
%      clustersTree{1, i}.dimensionality:the dimensionality of the subspace 
%                                         set(integer)
%      clustersTree{1, i}.coverage: the coverage of each subspace set(1-by-~)
%      clustersTree{1, i}.subspace: the subspace set ги1-by-~)
%                                   (each element of the set can be regaded
%                                   as  a subspace . )
%      
%  dataGrid : a matrix which indicated the grid that each point belongs to.
%             The NO.j dimension of NO.i point belongs to NO.dataGrid (i,j)
%             grid of the dimension(N-by-dimen)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%OUTPUT%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% clusterResult: a tree which contains the information about the label of
%                points
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%VERSION%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Author: Shuai Wu
%  Date : July 16 2018 
%  E_mail: shuaiwu.ws@gmail.com
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%END%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subspaceSet.dimensionality = [];
subspaceSet.subspace = [];
clusterResult = [];

for i = 1:size(clustersTree,2)
    subspaceSet.subspace = [];
    subspaceSet.dimensionality = clustersTree{1,i}.dimensionality;
    for j = 1:size(clustersTree{1,i}.subspace,2)
        if isempty(subspaceSet.subspace)
           subspaceSet.subspace = {labelPoints(clustersTree{1,i}.subspace{1,j},...
               dataGrid)};
        else
             subspaceSet.subspace = {subspaceSet.subspace{1,:},labelPoints(...
                 clustersTree{1,i}.subspace{1,j},dataGrid)};
        end
    end
    if isempty(clusterResult)
        clusterResult = {subspaceSet};
    else
        clusterResult = {clusterResult{1,:},subspaceSet};
    end
end

end
